import { afterEach, describe, expect, it, vi } from "vitest";
import type { JournalEntry } from "../src/shared/types";
import { Autosave, deletedEntryRecovery, draftKey, draftOf } from "../src/journal/Autosave";
import { ApiError } from "../src/api";
const entry:JournalEntry={id:"one",title:"Fern",content:"Original",tags:[],plantIds:[],terrariumIds:[],createdAt:"2026-08-27T10:00:00Z",updatedAt:"2026-08-27T10:00:00Z",recordedAt:"2026-08-27T10:00:00Z",entryDate:"2026-08-27",revision:1};
function memory(){const items=new Map<string,string>();return {getItem:(key:string)=>items.get(key)||null,setItem:(key:string,value:string)=>{items.set(key,value)},removeItem:(key:string)=>{items.delete(key)}}}
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r});return {promise,resolve}}
afterEach(()=>vi.useRealTimers());
describe("ordered diary autosave",()=>{
  it("does not save on opening and debounces actual changes",async()=>{vi.useFakeTimers();const save=vi.fn(async payload=>({...entry,...payload,revision:2}));const session=new Autosave(entry,save);await vi.advanceTimersByTimeAsync(1000);expect(save).not.toHaveBeenCalled();session.change({content:"new"});await vi.advanceTimersByTimeAsync(699);expect(save).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(1);expect(save).toHaveBeenCalledOnce();expect(session.snapshot.state).toBe("saved");session.dispose()});
  it("queues newer typing behind one in-flight request without marking it saved early",async()=>{const first=deferred<JournalEntry>(),second=deferred<JournalEntry>();const save=vi.fn().mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise),storage=memory();const session=new Autosave(entry,save,storage);session.change({content:"first"});const flush=session.flush();session.change({content:"latest"});expect(save).toHaveBeenCalledOnce();first.resolve({...entry,content:"first",revision:2});await Promise.resolve();await Promise.resolve();expect(session.snapshot.entry.content).toBe("latest");expect(session.dirty).toBe(true);expect(save.mock.calls[1][0].expectedRevision).toBe(2);second.resolve({...entry,content:"latest",revision:3});expect(await flush).toBe(true);expect(session.snapshot.entry.content).toBe("latest");expect(storage.getItem(draftKey(entry.id))).toBeNull();session.dispose()});
  it("keeps failed writes recoverable and retries explicitly",async()=>{const storage=memory(),save=vi.fn().mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce({...entry,content:"draft",revision:2});const session=new Autosave(entry,save,storage);session.change({content:"draft"});expect(await session.flush()).toBe(false);expect(session.snapshot.state).toBe("error");const recovery=new Autosave(entry,save,storage);expect(recovery.snapshot.recovered).toBe(true);expect(recovery.snapshot.entry.content).toBe("draft");expect(await recovery.flush()).toBe(true);session.dispose();recovery.dispose()});
  it.each([409,404])("stops on a %s response instead of overwriting or resurrecting an entry",async status=>{const save=vi.fn().mockRejectedValue(new ApiError("conflict",status)),session=new Autosave(entry,save,memory());session.change({title:"Local title"});await session.flush();expect(session.snapshot.state).toBe("conflict");session.change({content:"still writing"});expect(await session.flush()).toBe(false);expect(save).toHaveBeenCalledOnce();expect(session.snapshot.entry.title).toBe("Local title");session.dispose()});
  it("detects stale recovery drafts and tolerates unavailable browser storage",()=>{const storage=memory();storage.setItem(draftKey(entry.id),JSON.stringify({revision:1,draft:{...draftOf(entry),content:"unsaved"}}));const session=new Autosave({...entry,revision:2},vi.fn(),storage);expect(session.snapshot.state).toBe("conflict");expect(session.snapshot.entry.content).toBe("unsaved");session.dispose();const disabled={getItem:()=>{throw Error()},setItem:()=>{throw Error()},removeItem:()=>{throw Error()}};const fallback=new Autosave(entry,vi.fn(),disabled);fallback.change({content:"draft"});expect(fallback.snapshot.storageWarning).not.toBe("");fallback.dispose()});
  it("recovers writing after the server entry was deleted and never silently recreates it",async()=>{
    const storage=memory(),first=new Autosave(entry,vi.fn(),storage);first.change({content:"Still here"});first.dispose();
    const recovered=deletedEntryRecovery(entry.id,storage)!;expect(recovered.content).toBe("Still here");expect(recovered.recordedAt).toBe(entry.recordedAt);
    const save=vi.fn(),session=new Autosave(recovered,save,storage);expect(session.snapshot.error).toContain("deleted elsewhere");expect(await session.flush()).toBe(false);expect(save).not.toHaveBeenCalled();session.dispose();
  });
});
