export type PlantStatus = "healthy" | "needs_attention" | "recovering" | "dormant" | "deceased";
export type CareActivityType = "watering" | "misting" | "light" | "humidity" | "temperature" | "fertilization" | "pruning" | "repotting" | "custom";
export type HistoryEventType = "acquired" | "moved" | "terrarium_added" | "terrarium_removed" | "health_issue" | "recovery" | "flowering" | "new_growth" | "repotted" | "pruned" | "death" | "note";

export interface Species { id:string; commonName:string; scientificName:string; family:string; description:string; nativeHabitat:string; growthCharacteristics:string; matureSize:string; lightRequirements:string; waterRequirements:string; humidityRequirements:string; temperatureRange:string; substratePreferences:string; fertilizationRecommendations:string; propagationMethods:string; commonProblems:string; commonPests:string; toxicity:string; terrariumSuitability:string; notes:string; imageUrl:string; plantCount:number; createdAt:string; updatedAt:string; }
export interface Plant { id:string; name:string; spriteImage:string; speciesId:string|null; speciesCommonName:string; speciesScientificName:string; description:string; dateAcquired:string; source:string; location:string; terrariumId:string|null; terrariumName:string; status:PlantStatus; profilePhotoId:string|null; profilePhotoUrl:string; archivedAt:string|null; dateOfDeath:string; causeOfDeath:string; finalNotes:string; tags:string[]; updatedAt:string; createdAt:string; careItems?:CareItem[]; photos?:Photo[]; history?:TimelineItem[]; journalEntries?:JournalEntry[]; }
export interface Terrarium { id:string; name:string; spriteImage:string; description:string; dateCreated:string; type:string; location:string; lightingSetup:string; humidityRequirements:string; wateringNotes:string; substrateInformation:string; notes:string; otherInhabitants:string; coverPhotoId:string|null; coverPhotoUrl:string; plantCount:number; plants?:Plant[]; photos?:Photo[]; journalEntries?:JournalEntry[]; history?:TimelineItem[]; createdAt:string; updatedAt:string; }
export interface CareItem { id:string; plantId:string; activityType:CareActivityType; customLabel:string; guidance:string; cadenceDays:number|null; reminderEnabled:boolean; nextReminderDate:string; notes:string; sortOrder:number; }
export interface Photo { id:string; plantId:string|null; terrariumId:string|null; url:string; originalName:string; mimeType:string; sizeBytes:number; dateTaken:string; caption:string; tags:string[]; createdAt:string; }
export interface JournalEntry { id:string; title:string; entryDate:string; content:string; tags:string[]; plantIds:string[]; terrariumIds:string[]; linkedPlants?:Pick<Plant,"id"|"name">[]; linkedTerrariums?:Pick<Terrarium,"id"|"name">[]; createdAt:string; updatedAt:string; recordedAt:string; revision:number; }
export interface TimelineItem { id:string; kind:"event"|"photo"|"journal"; eventType?:HistoryEventType; date:string; title:string; detail:string; photoUrl?:string; journalId?:string; }
export interface DashboardGardenItem { id:string; name:string; spriteImage:string; }
export interface DashboardData { livingPlants:number; terrariums:number; gardenPlants:DashboardGardenItem[]; gardenTerrariums:DashboardGardenItem[]; attentionPlants:Plant[]; recentlyUpdated:Plant[]; recentJournals:JournalEntry[]; recentPhotos:Photo[]; upcomingReminders:Array<CareItem & {plantName:string}>; }
export interface AppNotifications { attentionCount:number; attentionPlants:Array<{id:string;name:string;status:PlantStatus;spriteImage:string}>; attentionTerrariums:Array<{id:string;name:string;residentAttentionCount:number;spriteImage:string}>; }
export interface GlobalSearchResult { id:string; type:"plant"|"species"|"terrarium"|"journal"; title:string; subtitle:string; url:string; spriteImage?:string; }
export interface AppOptions { species:Species[]; terrariums:Terrarium[]; tags:string[]; }

export interface JournalTag { id:string; name:string; entryCount:number; }
export interface JournalImage { id:string; journalId:string; url:string; originalName:string; mimeType:string; sizeBytes:number; }
